<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="Facultydetail.aspx.cs" Inherits="Admin_Facultydetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
        &nbsp;</p>
    <p style="text-align: center">
        <asp:Label ID="Label1" runat="server" 
            style="font-size: xx-large; font-weight: 700; color: #33CC33" 
            Text="Faculty Detail"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            DataKeyNames="ID" DataSourceID="SqlDataSource1" Width="774px" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" 
            CellPadding="4" GridLines="Horizontal" 
            onselectedindexchanged="GridView1_SelectedIndexChanged" 
            style="margin-left: 217px">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" 
                    SortExpression="ID" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Phone_No" HeaderText="Phone_No" 
                    SortExpression="Phone_No" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Department" HeaderText="Department" 
                    SortExpression="Department" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Qualification" HeaderText="Qualification" 
                    SortExpression="Qualification" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Designation" HeaderText="Designation" 
                    SortExpression="Designation" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Address" HeaderText="Address" 
                    SortExpression="Address" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Gender" HeaderText="Gender" 
                    SortExpression="Gender" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Password" HeaderText="Password" 
                    SortExpression="Password" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#333333" />
            <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#487575" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" 
            SelectCommand="SELECT DISTINCT * FROM [Faculty_Registration]"
            UpdateCommand="Update [Faculty_Registration] set  ID=@ID,Name=@Name,Email=@Email,Phone_No=@Phone_No,Department=@Department,Qualification=@Qualification,Designation=@Designation,City=@City,Address=@Address,Gender=@Gender,Password=@Password where ID=@ID"
            DeleteCommand="Delete[Faculty_Registration] where ID=@ID" onselecting="SqlDataSource1_Selecting">
            <UpdateParameters>
            <asp:Parameter Name="ID" />
            <asp:Parameter Name="Name" />
            <asp:Parameter Name="Email" />
            <asp:Parameter Name="Phone_No" />
            <asp:Parameter Name="Department" />
            <asp:Parameter Name="Qualification" />
            <asp:Parameter Name="Designation" />
            <asp:Parameter Name="City" />
            <asp:Parameter Name="Address" />
            <asp:Parameter Name="Gender" />
            <asp:Parameter Name="Password" />
            </UpdateParameters>
            <DeleteParameters>
            <asp:Parameter Name="ID" />
            </DeleteParameters>
        </asp:SqlDataSource>
            
    </p>
    <p>
        &nbsp;</p>
</asp:Content>

