<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="Studentdetail.aspx.cs" Inherits="Admin_Studentdetail" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  

    <p>
        &nbsp;</p>
    <p style="text-align: center">
        <asp:Label ID="Label1" runat="server" 
            style="font-weight: 700; color: #33CC33; font-size: xx-large; text-align: center" 
            Text="Student Detail"></asp:Label>
        <br />
    </p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            DataKeyNames="RollNo" DataSourceID="SqlDataSource1" BackColor="White" 
            BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
            GridLines="Horizontal" HorizontalAlign="Center">
            <Columns>
                <asp:BoundField DataField="RollNo" HeaderText="RollNo" ReadOnly="True" 
                    SortExpression="RollNo" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Phone_No" HeaderText="Phone_No" 
                    SortExpression="Phone_No" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Department" HeaderText="Department" 
                    SortExpression="Department" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Batch" HeaderText="Batch" SortExpression="Batch" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Branch" HeaderText="Branch" 
                    SortExpression="Branch" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Address" HeaderText="Address" 
                    SortExpression="Address" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Gender" HeaderText="Gender" 
                    SortExpression="Gender" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
                <asp:BoundField DataField="Password" HeaderText="Password" 
                    SortExpression="Password" >
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#333333" />
            <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#487575" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" 
            SelectCommand="SELECT DISTINCT * FROM [Stu_registration]"
            UpdateCommand="Update [Stu_registration] set  RollNo=@RollNo,Name=@Name,Email=@Email,Phone_No=@Phone_No,Department=@Department,Batch=@Batch,Branch=@Branch,Address=@Address,DOB=@DOB,Gender=@Gender,Password=@Password where RollNo=@RollNo"
            DeleteCommand="Delete[Stu_registration] where RollNo=@RollNo" onselecting="SqlDataSource1_Selecting">
            <UpdateParameters>
            <asp:Parameter Name="RollNo" />
            <asp:Parameter Name="Name" />
            <asp:Parameter Name="Email" />
            <asp:Parameter Name="Phone_No" />
            <asp:Parameter Name="Department" />
            <asp:Parameter Name="Batch" />
            <asp:Parameter Name="Branch" />
            <asp:Parameter Name="Address" />
            <asp:Parameter Name="DOB" />
            <asp:Parameter Name="Gender" />
            <asp:Parameter Name="Password" />
            </UpdateParameters>
            <DeleteParameters>
            <asp:Parameter Name="RollNo" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </p>
  

    </asp:Content>

